version: "3.8"

services:
    meteo-db:
        build:
            context: ./meteo-db
            dockerfile: Dockerfile
        ports:
            - 127.0.0.1:5432:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - db-data:/var/lib/postgresql/data:delegated
        container_name: meteo-db
        networks:
            - meteo-network
        restart: always

    meteo-migrations:
        image: flyway/flyway
        command: -configFiles=/flyway/conf/flyway.conf -locations=filesystem:/flyway/sql -connectRetries=60 migrate
        volumes:
            - ${PWD}/meteo-migrations/flyway/sql:/flyway/sql
            - ${PWD}/meteo-migrations/flyway/conf/flyway.conf:/flyway/conf/flyway.conf
        container_name: meteo-migrations
        environment:
            - FLYWAY_USER=${FLYWAY_USER}
            - FLYWAY_PASSWORD=${FLYWAY_PASSWORD}
        networks:
            - meteo-network
        depends_on:
            - meteo-db
        restart: always

    meteo-flow:
        build:
            context: ./meteo-flow
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        environment:
            - FLYWAY_USER=${FLYWAY_USER}
            - FLYWAY_PASSWORD=${FLYWAY_PASSWORD}
            - FLYWAY_PLACEHOLDERS_AIRFLOW_USER=${AIRFLOW_DB_USER}
            - FLYWAY_PLACEHOLDERS_AIRFLOW_PASSWORD=${AIRFLOW_DB_PASSWORD}
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@meteo-db/meteo
        container_name: meteo-flow
        networks:
            - meteo-network
        depends_on:
            - meteo-db
            - meteo-migrations
        restart: always

    meteo-api:
        build:
            context: ./meteo-api
            dockerfile: Dockerfile
        ports:
            - 127.0.0.1:8090:8090
        environment:
            - PGUSER=${METEO_API_PGUSER}
            - PGHOST=${METEO_API_PGHOST}
            - PGPASSWORD=${METEO_API_PGPASSWORD}
            - PGDATABASE=${METEO_API_PGDATABASE}
            - PGPORT=${METEO_API_PGPORT}
        container_name: meteo-api
        networks:
            - meteo-network
        depends_on:
            - meteo-db
        restart: always

    meteo-app:
        build:
            context: ./meteo-app
            dockerfile: Dockerfile.prod
        ports:
            - 127.0.0.1:3000:80
        environment:
            - METEO_API_URL=${METEO_API_URL}
        container_name: meteo-app
        networks:
            - meteo-network
        depends_on:
            - meteo-api
        restart: always

volumes:
    db-data:

networks:
    meteo-network:
        driver: bridge
