SET search_path TO imgw;

-- http://danepubliczne.imgw.pl/data/dane_pomiarowo_obserwacyjne/dane_meteorologiczne/dobowe/synop/

CREATE TABLE synop_daily (
    station_id BIGINT NOT NULL REFERENCES imgw.station (id),
    date DATE GENERATED ALWAYS AS (make_date(year, month, day)) STORED,
    year SMALLINT NOT NULL,
    month SMALLINT NOT NULL,
    day SMALLINT NOT NULL,
    tmax NUMERIC NOT NULL,
    tmax_status CHAR(1),
    tmin NUMERIC NOT NULL,
    tmin_status CHAR(1),
    tavg NUMERIC NOT NULL,
    tavg_status CHAR(1),
    tmin_ground NUMERIC NOT NULL,
    tmin_ground_status CHAR(1),
    smdb NUMERIC,
    smdb_status CHAR(1),
    smsdb_type CHAR(1),
    pksn NUMERIC,
    pksn_status CHAR(1),
    rwsn NUMERIC,
    rwsn_status CHAR(1),
    usl NUMERIC,
    usl_status CHAR(1),
    desz NUMERIC,
    desz_status CHAR(1),
    sneg NUMERIC,
    sneg_status CHAR(1),
    disn NUMERIC,
    disn_status CHAR(1),
    grad NUMERIC,
    grad_status CHAR(1),
    mgla NUMERIC,
    mgla_status CHAR(1),
    zmgl NUMERIC,
    zmgl_status CHAR(1),
    sadz NUMERIC,
    sadz_status CHAR(1),
    golo NUMERIC,
    golo_status CHAR(1),
    zmni NUMERIC,
    zmni_status CHAR(1),
    zmws NUMERIC,
    zmws_status CHAR(1),
    zmet NUMERIC,
    zmet_status CHAR(1),
    ff10 NUMERIC,
    ff10_status CHAR(1),
    ff15 NUMERIC,
    ff15_statsu CHAR(1),
    brza NUMERIC,
    brza_status CHAR(1),
    rosa NUMERIC,
    rosa_status CHAR(1),
    szro NUMERIC,
    szro_status CHAR(1),
    dzps SMALLINT,
    dzps_status CHAR(1),
    dzbl SMALLINT,
    dzbl_status CHAR(1),
    sg CHAR(1),
    izd NUMERIC,
    izd_status CHAR(1),
    izg NUMERIC,
    izg_status CHAR(1),
    aktn NUMERIC,
    aktn_status CHAR(1)
);

CREATE UNIQUE INDEX ON synop_daily (station_id, year, month, day);
CREATE INDEX ON synop_daily (year, month, day);